version: "3.1"

services:
  database:
    image: postgres
    container_name: pgdb-go-with-gin
    env_file: ../.env
    ports:
      - 5432:5432
    volumes:
      - ./initial_scripts/create-albums-table.sql:/docker-entrypoint-initdb.d/create-albums-table.sql
